### ISSUE TITLE
qa for price override 

### ISSUE THREAD

**Issue by BeanieMen** [BeanieMen/ubiquibot#10]
[qa](https://github.com/ubiquity/ubiquibot/pull/735)

**Comment by BeanieMen** [comment]
didnt reset the price good good

**Comment by BeanieMen** [comment]
Wait le me start the bot again

**Comment by wannacfuture** [comment]
Could you check the logger?

**Comment by BeanieMen** [comment]
yep same in the logger

**Comment by wannacfuture** [comment]
> yep same in the logger

I left the comment on your PR.

**Comment by BeanieMen** [comment]
@wannacfuture i hardcoded the value for conv reward

**Comment by wannacfuture** [comment]
lol that's a really temporarily solution.

**Comment by BeanieMen** [comment]
But it still works right 💀 it's generating rewards for 25 wxdai
