### ISSUE TITLE
price override

### ISSUE THREAD

**Issue by BeanieMen** [BeanieMen/ubiquibot#6]

**Comment by BeanieMen** [comment]
it worked?

**Comment by BeanieMen** [comment]
ye boi

**Comment by BeanieMen** [comment]
it didnt reset so thats a plus

**Comment by 0x4007** [comment]
> Permit generation skipped because wallet private key is not set
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

Set a private key so we can see the amount it generates. It must be the same as the price tag.

**Comment by BeanieMen** [comment]
@pavlovcik I wouldn't have to make a org account right, just a ubiquibot-config repo with the config plus encrypted private key

**Comment by BeanieMen** [comment]
/

**Comment by BeanieMen** [comment]
its working
